package com.attendanceio.api.application.agent

import com.attendanceio.api.application.agent.actions.AgentAnalyticsQueryAppAction
import com.attendanceio.api.application.agent.actions.AgentCatalogAppAction
import com.attendanceio.api.application.agent.actions.AgentMyQueryAppAction
import com.attendanceio.api.application.agent.actions.AgentPlanningQueryAppAction
import com.attendanceio.api.application.agent.actions.AgentStudentQueryAppAction
import com.attendanceio.api.application.agent.tools.AgentToolSupport
import com.attendanceio.api.application.agent.tools.AnalyticsAgentTools
import com.attendanceio.api.application.agent.tools.CatalogAgentTools
import com.attendanceio.api.application.agent.tools.MyAttendanceAgentTools
import com.attendanceio.api.application.agent.tools.PlanningAgentTools
import com.attendanceio.api.application.agent.tools.StudentAgentTools
import com.attendanceio.api.config.AgentProperties
import com.attendanceio.api.model.agent.AgentMyAttendance
import org.junit.jupiter.api.Test
import org.mockito.Mockito.mock
import org.mockito.Mockito.`when`
import org.springframework.ai.chat.model.ToolContext
import org.springframework.ai.tool.method.MethodToolCallbackProvider
import tools.jackson.databind.json.JsonMapper
import java.time.LocalDate
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * The tool menu is generated by reflection from Kotlin signatures. This pins down the three things
 * that would break silently otherwise: every tool is discovered, parameter names survive
 * compilation (not `arg0`), and the ToolContext parameter never leaks into the schema the model
 * sees. It also exercises one full call through the recorder with a fake caller.
 */
class AgentToolSchemaTest {
    private val support = AgentToolSupport(JsonMapper.builder().build())
    private val properties = AgentProperties()
    private val myQuery = mock(AgentMyQueryAppAction::class.java)
    private val studentQuery = mock(AgentStudentQueryAppAction::class.java)
    private val catalog = mock(AgentCatalogAppAction::class.java)
    private val analytics = mock(AgentAnalyticsQueryAppAction::class.java)
    private val planning = mock(AgentPlanningQueryAppAction::class.java)

    private val toolObjects = arrayOf<Any>(
        MyAttendanceAgentTools(myQuery, support),
        StudentAgentTools(studentQuery, support, properties),
        CatalogAgentTools(catalog, support),
        AnalyticsAgentTools(analytics, support),
        PlanningAgentTools(planning, support)
    )

    private val callbacks = MethodToolCallbackProvider.builder().toolObjects(*toolObjects).build().toolCallbacks

    @Test
    fun `every tool is discovered with its declared name`() {
        val names = callbacks.map { it.toolDefinition.name() }.sorted()
        assertEquals(
            listOf(
                "compare_students", "get_academic_calendar", "get_attendance_on_date", "get_attendance_trend",
                "get_group_average", "get_lab_tutorial_attendance", "get_my_attendance", "get_my_timetable",
                "get_overall_analytics", "get_student_attendance", "get_subject_class_stats", "get_subject_records",
                "get_subject_schedule", "get_unmarked_lectures", "list_semesters", "list_subjects", "search_students",
                "simulate_attendance"
            ),
            names
        )
    }

    @Test
    fun `schemas use real parameter names and hide the tool context`() {
        val byName = callbacks.associateBy { it.toolDefinition.name() }
        val records = byName.getValue("get_subject_records").toolDefinition.inputSchema()
        assertTrue("\"subject\"" in records, records)
        assertTrue("\"studentId\"" in records, records)
        assertFalse("toolContext" in records, records)
        assertFalse("arg0" in records, records)
        val search = byName.getValue("search_students").toolDefinition.inputSchema()
        assertTrue("\"query\"" in search && "required" in search, search)
    }

    @Test
    fun `a call runs through the caller context and the recorder`() {
        val caller = AgentCaller(email = "202301001@dau.ac.in", studentId = 42, name = "Test", rollNumber = "202301001", isDemo = false)
        val recorder = AgentToolCallRecorder()
        `when`(myQuery.myAttendance(42, LocalDate.parse("2026-09-01")))
            .thenReturn(AgentMyAttendance("2026-09-01", emptyList(), emptyList(), "none"))

        val tool = callbacks.first { it.toolDefinition.name() == "get_my_attendance" }
        val context = ToolContext(mapOf(AgentToolCallRecorder.CALLER_KEY to caller, AgentToolCallRecorder.CONTEXT_KEY to recorder))
        val result = tool.call("""{"asOfDate":"2026-09-01"}""", context)

        assertTrue("2026-09-01" in result, result)
        assertEquals(listOf("get_my_attendance"), recorder.snapshot().map { it.name })
        assertEquals(null, recorder.snapshot().single().error)
    }

    @Test
    fun `the recorder announces each tool as it starts`() {
        val started = mutableListOf<String>()
        val recorder = AgentToolCallRecorder(onStart = { started += it })
        val caller = AgentCaller(email = "202301001@dau.ac.in", studentId = 42, name = "Test", rollNumber = "202301001", isDemo = false)
        val tool = callbacks.first { it.toolDefinition.name() == "get_academic_calendar" }
        val context = ToolContext(mapOf(AgentToolCallRecorder.CALLER_KEY to caller, AgentToolCallRecorder.CONTEXT_KEY to recorder))
        `when`(planning.calendar()).thenReturn(
            com.attendanceio.api.model.agent.AgentAcademicCalendar(null, "2026-07-22", "2026-11-20", "2026-09-19", 9, 44)
        )
        tool.call("{}", context)
        assertEquals(listOf("get_academic_calendar"), started)
    }

    @Test
    fun `a personal tool refuses an account without a student record`() {
        val caller = AgentCaller(email = "someone@gmail.com", studentId = null, name = null, rollNumber = null, isDemo = true)
        val recorder = AgentToolCallRecorder()
        val tool = callbacks.first { it.toolDefinition.name() == "get_my_timetable" }
        val context = ToolContext(mapOf(AgentToolCallRecorder.CALLER_KEY to caller, AgentToolCallRecorder.CONTEXT_KEY to recorder))

        val result = runCatching { tool.call("{}", context) }
        // Spring AI reports tool failures back to the model as text rather than throwing.
        val text = result.getOrNull() ?: result.exceptionOrNull()?.message.orEmpty()
        assertTrue("not linked to a student record" in text, text)
        assertEquals("get_my_timetable", recorder.snapshot().single().name)
        assertTrue(recorder.snapshot().single().error != null)
    }
}
